# Generated by Django 5.2 on 2025-04-12 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название книги', max_length=255, verbose_name='Название книги')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, help_text='Не может быть отрицательным', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Общее количество проданных экземпляров', verbose_name='Продано экземпляров')),
                ('price', models.IntegerField(help_text='Цена в рублях', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('cover_image', models.ImageField(blank=True, help_text='Изображение обложки', null=True, upload_to='books/covers/%Y/%m/%d/', verbose_name='Обложка книги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
